// generated by `sqlx migrate build-script`
fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::configure()
        .build_server(true)
        .compile(
            &[
                "../../proto/valorem/trade/v1/rfq.proto",
                "../../proto/valorem/trade/v1/auth.proto",
            ],
            &["../../proto/valorem/trade/v1/"], // specify the root location to search proto dependencies
        )
        .unwrap();
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    Ok(())
}
